version: "3"
services:
  db:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./conduit:/data/db/
    ports:
      - "27017:27017"
  node_express_app:
    container_name: node_express_app
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://db:27017/
    depends_on:
      - db