version: "3"
networks:
  app-tier:
    driver: bridge
services:
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 27027 --storageEngine=wiredTiger
    restart: always
    volumes:
      - ./conduit:/data/db/
      #- ./tests/data:/data
    ports:
      - "27027:27027"

  node_express_app:
    container_name: node_express_app
    restart: always
    build: .
    volumes:
      - ".:/app"
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
      - SECRET=conduit
      - MONGODB_URI=mongodb://mongo:27027/conduit
    depends_on:
      - mongo