version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 27017 --storageEngine=wiredTiger
    restart: always
    volumes:
      - ./conduit:/data/db/
    ports:
      - "27021:27017"

  node_express_app:
    container_name: node_express_app
    restart: always
    build: .
    #volumes:
    #  - ".:/app"
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
      - SECRET=conduit
      - MONGODB_URI=mongodb://mongo:27017/conduit
    depends_on:
      - mongo